### ISSUE TITLE
Challenge Error (Could not pass event InventoryClickEvent) : ASkyBlock v3.0.3.2

### ISSUE THREAD

**Issue by Steev93** [tastybento/askyblock#307] opened 2016-09-06 05:57 UTC
> 05.09 22:55:14 [Server] ERROR Could not pass event InventoryClickEvent to ASkyBlock v3.0.3.2
> 05.09 22:55:14 [Server] INFO org.bukkit.event.EventException
> 05.09 22:55:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1850) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
> 05.09 22:55:14 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
> 05.09 22:55:14 [Server] INFO Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'asc' in plugin ASkyBlock v3.0.3.2
> 05.09 22:55:14 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:278) ~[?:?]
> 05.09 22:55:14 [Server] INFO at sun.reflect.GeneratedMethodAccessor305.invoke(Unknown Source) ~[?:?]
> 05.09 22:55:14 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
> 05.09 22:55:14 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
> 05.09 22:55:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
> 05.09 22:55:14 [Server] INFO ... 15 more
> 05.09 22:55:14 [Server] INFO Caused by: java.lang.NullPointerException
> 05.09 22:55:14 [Multicraft] Skipped 15 lines due to rate limit (30/s)

When doing Challenge

> ```
> howarbitrary:
>   friendlyname: 'How Arbitraty'
>   description: 'Collect 13 Melon Seed, 1 Wooden Axe, 2 Crafting Table, 26 Cooked Fish, 134 Stone Brick Slabs, 37 Cobblestone, 7 Dirt, 4 Grass & 65 Cracked Stone Brick'
>   icon: WOOD_AXE
>   level: 'level6'
>   type: inventory
>   requiredItems: 'WOOD_AXE:1 MELON_SEEDS:13 WORKBENCH:2 COOKED_FISH:26 STONE_SLAB:5:134 COBBLESTONE:37 DIRT:7 GRASS:4 SMOOTH_BRICK:2:65'
>   takeItems: true
>   itemReward: 'IRON_ORE:12 DIRT:8'
>   rewardcommands: ''
>   rewardText: '12 Iron ore and 8 Dirt'
>   moneyReward: 80
>   expReward: 110
>   permissionReward: ''
>   repeatable: true
>   repeatItemReward: 'IRON_ORE:3 DIRT:2'
>   repeatRewardText: '3 Iron ore and 2 Dirt'
>   repeatMoneyReward: 110
>   repeatExpReward: 85
>   # Max times limits how many times a challenge can be done. Comment out to make unlimited
>   maxtimes: 25
> ```

**Comment by Creatif** [comment] 2016-09-06 18:21
Try **STEP:5:134** instead of **STONE_SLAB:5:134**
(maybe, im not sure)

**Comment by Steev93** [comment] 2016-09-06 21:08
@Creatif 
You need the right code for it tho, i got these from here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

However i will see what @tastybento  says :)

**Comment by Creatif** [comment] 2016-09-06 22:00
STONE_SLAB do not exit in bukkit.

STONE_SLAB2 exist, but I think you want STEP:5:134 :). Try it !

**Comment by tastybento** [comment] 2016-09-07 01:00
Yes, it's correct - SLAB.

**Comment by Steev93** [comment] 2016-09-07 03:26
Thanks will adjust this shortly and respond

**Comment by Steev93** [comment] 2016-09-08 05:10
> Yes, it's correct - SLAB.

Yes however still fails to work, i would check console but because of the other challenge Error and i'm using the 3.0.3.3 as to this #301 this is also not working. As you said console would be spammed

**Comment by L4BORG** [comment] 2016-09-12 13:00
I think we have the same issue:

```
[14:54:16] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ASkyBlock v3.0.3.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1662) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'asc' in plugin ASkyBlock v3.0.3.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:278) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor310.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	... 16 more
Caused by: java.lang.NullPointerException
	at com.wasteofplastic.askyblock.commands.Challenges.hasRequired(Challenges.java:1205) ~[?:?]
	at com.wasteofplastic.askyblock.commands.Challenges.checkIfCanCompleteChallenge(Challenges.java:828) ~[?:?]
	at com.wasteofplastic.askyblock.commands.Challenges.onCommand(Challenges.java:198) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:278) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor310.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	... 16 more
```

Running A Skyblock V3.0.3.2 from spigotmc.org

```
>ver
[01:24:54 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
```

With default challenges...

**Comment by tastybento** [comment] 2016-09-12 17:45
@L4BORG Which challenge are you trying to complete?

**Comment by tastybento** [comment] 2016-09-12 17:46
I'm out of the country right now so i can't check into this for a week or so, but I'll look at it when i get back.

**Comment by Steev93** [comment] 2016-09-13 11:57
@tastybento  all good take your time, as i have told people in my server just waiting on a patch update so all good :)

**Comment by L4BORG** [comment] 2016-09-24 16:41
I'm not sure, random player was trying to complete challenge I wasn't online I just saw exception in console :/

**Comment by L4BORG** [comment] 2016-09-24 16:42
We're using default challenges.yml (I think): http://pastebin.com/Xvmw9Keq

**Comment by tastybento** [comment] 2016-09-24 17:09
@Steev93 I just tested your challenge and it works okay if I use SLAB. Here's the inventory I had:
https://i.gyazo.com/0ab33fcebf84ba58e703809a77818147.png
Then I clicked the axe:
https://i.gyazo.com/2752fbc1810a629f91adde7fa3e1ff58.png
Here's the challenge line:
requiredItems: 'WOOD_AXE:1 MELON_SEEDS:13 WORKBENCH:2 COOKED_FISH:26 STEP:5:134 COBBLESTONE:37 DIRT:7 GRASS:4 SMOOTH_BRICK:2:65'

**Comment by tastybento** [comment] 2016-09-24 17:11
@L4BORG Your issue is different. It's something to do with Potions and 1.8.8. Checking now.

**Comment by tastybento** [comment] 2016-09-24 17:27
@L4BORG Do you have any custom potions on your server? It looks like there was a potion in the player's inventory that had a null name. This shouldn't happen with the standard potions, but maybe they had a custom one somehow?

**Comment by L4BORG** [comment] 2016-09-24 17:43
@tastybento hm, can't think of anything right now, we're not using McMMo or anything like that, but players can buy some potions (we're using Essentials [buy] signs).

**Comment by tastybento** [comment] 2016-09-25 20:06
Hmm, well I added a null check for that situation just in case, but it'd be nice to know the root cause. The change will be in the next version.

**Closed** 2016-11-12 15:41 UTC
Labels: question
