### ISSUE TITLE
Problems with world guard after convert usb>asb

### ISSUE THREAD

**Issue by johnsoncui02** [tastybento/askyblock#413] opened 2016-12-17 17:12 UTC
Background: I used uacovert and was originally using uskyblock. after converting to askyblock there's been issues.

1. The world guard does not generate protection for starting players with new island new regions does not have ownership of the person creating the island.
 - because there's no world guard ownership players cannot open chest, break block , etc etc. It's a very critical problem for the players.
2. Nether world does not generate (the config for new nether is set to true and true on everything else in nether.
3. /is reset or /is restart does not work for older players. error message: (You need to kick all the players in your team before you can reset the island) [Even though there's only one person in the team).

**Comment by tastybento** [comment] 2016-12-17 17:39
1. ASkyBlock doesn't use WorldGuard. You should delete all the old worldguard protection for the skyblock world so that there isn't duplication.

You may need to have the islands.yml regenerated to obtain all the latest settings. You can do this by stopping the server, deleting islands.yml and restarting.

2. For the nether, stop the server, delete the skyblock nether world completely (the folder), then restart.

3. This is a problem with uSkyblock data being buggy. Hmm, can you look at their status using asadmin commands and see if you can kick fake team members? You may need to edit their yml file directly. I'd like to see the yml file of a player that is affected. Can you paste it (pastebin.com)?

**Comment by johnsoncui02** [comment] 2016-12-17 17:54
also. just to add to that, all the older people from uskyblock cannot seem to generate their old island home. rather I have to manually tp to them to resolve this issue.

**Comment by johnsoncui02** [comment] 2016-12-17 17:55
question: so if askyblock does not use worldguard, how does it protect itself from other players?

**Comment by tastybento** [comment] 2016-12-17 17:56
Protection is built into ASkyBlock.

I don't understand when you say they cannot generate their old island home - what do you mean? Is there an error?

**Comment by johnsoncui02** [comment] 2016-12-17 17:58
there's just no sethome what so ever. So far i've never seen a error from console. only from the ingame chat where it says the warp is not safe right now. try again later.

**Comment by johnsoncui02** [comment] 2016-12-17 18:01
and yes to respond to your question. the admin command does work to delete other player islands. thanks

**Comment by tastybento** [comment] 2016-12-17 18:01
You mean they don't have the /island sethome command? Maybe they don't have the permission?

**Comment by johnsoncui02** [comment] 2016-12-17 18:02
they don't have a home by default. which means if older member come back when i'm not on, and they didn't /is sethome and instead went to the /spawn. they would not be able to head back to their islands.

**Comment by tastybento** [comment] 2016-12-17 18:02
What might be the issue is that their old home position was not transferred over and they need to redo them.

**Comment by johnsoncui02** [comment] 2016-12-17 18:03
yup. that's what i was afraid of, thanks for all your quick responses, really appreciate it. your plugin is awesome. Will try the steps given right now.

**Comment by tastybento** [comment] 2016-12-17 18:03
Hmm, but it should still be possible for them to get to the island somehow because there is a search done for a safe spot, but it may be that a spot can't be found so easily.

**Comment by tastybento** [comment] 2016-12-17 18:04
By the way, watch out for the new release 3.0.5.2 - it fixes at least one major bug...

**Comment by johnsoncui02** [comment] 2016-12-17 18:06
yup. i got the plugin about 3 hours ago just to make sure all the updates are fine

**Comment by johnsoncui02** [comment] 2016-12-17 18:06
thanks for the warnings

**Comment by johnsoncui02** [comment] 2016-12-17 18:07
i probably downloaded about 20 times of askyblock just to try to get this converting thing to work lol. i expected issues because it's a completely different plugin

**Comment by johnsoncui02** [comment] 2016-12-17 18:09
if there's any more issues i'll notify you. thanks for your work once again.

**Comment by tastybento** [comment] 2016-12-17 18:10
Also, I recommend you migrate your converted config.yml to the commented config.yml because it will have a lot more settings and explanation for you. Good luck!

**Closed by tastybento** 2016-12-17 18:10 UTC
Labels: Support request

**Comment by johnsoncui02** [comment] 2016-12-17 18:12
yes i noticed from your step 12 or somewhat it mentioned over there. it helped me understand all the details. You should maybe add one more tip for world guard issues for upcoming converters who use the plugin tho. Just a thought

**Comment by johnsoncui02** [comment] 2016-12-17 18:13
just so people who have no clue like me can stop the fuzz lol
