### ISSUE TITLE
Request: The End Islands

### ISSUE THREAD

**Issue by forsco** [tastybento/askyblock#257] opened 2016-06-29 13:07 UTC
Hello,

Currently looking into options to change the End on our server to be like the Overworld and the Nether in regards to player islands.

Would this be at all possible to include as an optional feature within askyblock for server admins to use if they wish?

**Comment by forsco** [comment] 2016-07-02 15:37
@tastybento Is this feasible?

**Comment by tastybento** [comment] 2016-07-03 00:28
Honestly, I don't have the time to add it. It is possible to make an End world and then have players go there, but it's shared and you need to reset it if the dragon gets killed.

**Comment by tastybento** [comment] 2016-11-27 22:43
Dupe of #305

**Closed by tastybento** 2016-11-27 22:43 UTC
Labels: Feature request
