### ISSUE TITLE
/is level and /is topten

### ISSUE THREAD

**Issue by TGWaffles** [tastybento/askyblock#426] opened 2016-12-23 17:08 UTC
None of the island level tracking is working on our server. When a player runs /is level, this is what shows:

```
[17:58:40 INFO]: TGWaffles issued server command: /is level
[17:58:40 WARN]: Exception in thread "Craft Scheduler Thread - 1914"
[17:58:40 WARN]: org.apache.commons.lang.UnhandledException: Plugin ASkyBlock v3.0.5.1 generated an exception while executing task 1433597
       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArithmeticException
```

EDIT: Also, [WELCOME] signs don't seem to be working either, which may be linked to the above issues.

**Comment by tastybento** [comment] 2016-12-23 20:55
Is there any more of this error in the log? The error looks like it is coming from the server itself. Is the server modded? Did you compile it yourself?

**Comment by TGWaffles** [comment] 2016-12-24 00:18
The server's a basic Spigot server, which has been compiled and works fine for 49 other plugins. That error's the only one that we can't solve, so we brought it here. Any suggestions?

**Comment by tastybento** [comment] 2016-12-24 00:23
Are there any more lines to the error log?

**Comment by tastybento** [comment] 2016-12-24 00:24
Also, please post the error you see for Welcome signs.

**Comment by TGWaffles** [comment] 2016-12-24 16:41
That's all there is to the error message, and when placing a sign it fails and produces [this](http://prntscr.com/dnghlc) in game, which I can guess is caused by there not being any island level anyway. /is top produces no error, and shows an empty GUI with nothing in it.

**Comment by tastybento** [comment] 2016-12-24 19:28
Okay, thanks. Could you check what the **levelcost** value is in _blockvalues.yml_? "java.lang.ArithmeticException" is usually caused by a divide by zero condition. In the level calculations, that can happen if the levelcost is zero. The default value is 100.

If that's not the issue I'll keep looking. If you adjusted the blockvalues.yml file, please share it. I'd like to try and replicate.

**Comment by TGWaffles** [comment] 2016-12-24 21:33
That fixed the /is level thing and restored some order to /is top, thanks!
New issue, however - /is top shows [this](http://prntscr.com/dnjex7), and I'm not sure why. It has everything working, except there's no #1. Running /asadmin topten didn't fix it either.

**Comment by tastybento** [comment] 2016-12-25 01:53
Huh! Who is number one? Can you summon a head of that player?

**Comment by TGWaffles** [comment] 2016-12-25 02:31
Not too sure who number 1 (or 4) is, but I have a feeling that the player listed as number 2 is number one.
________________________________

**Comment by Poslovitch** [comment] 2016-12-27 23:30
Maybe we should add a debug command that can display top ten in chat?
There are 2 possibilities :
- Any player is considered as 1st or 4th by the plugin
- The head "generation" failed

**Comment by tastybento** [comment] 2016-12-28 05:05
@TGWaffles just look at the topten.yml file. It'll have a list of UUIDs and levels and you can then search for the UUID.

**Comment by tastybento** [comment] 2016-12-28 05:06
@Poslovitch The "debug" option could be to turn off the TopTen GUI and just display the legacy chat top ten. :-)

**Comment by TGWaffles** [comment] 2016-12-29 15:33
After some fiddling around, I managed to make it [show up](http://prntscr.com/dpc3zo), but I think I figured out why it wasn't showing before - http://prntscr.com/dpc4fr - he doesn't register as having an island while he does. Is there any way I could remove this players' island, as removing their data file from the players folder didn't remove them, and neither did removing them from topten.yml. They don't show up in islands.yml, and in-game I can't delete/unregister/remove their island at all as it doesn't exist. 

Thanks!

**Comment by tastybento** [comment] 2016-12-29 17:54
If that does work, then /asadmin delete (name)

**Comment by tastybento** [comment] 2016-12-29 17:55
Or go to their island and register them /asadmin register (name)

**Comment by TGWaffles** [comment] 2016-12-31 23:18
I can't go to their island as I can't determine where it is. Deleting them or unregistering them, as I said, doesn't work as they don't exist.

**Comment by tastybento** [comment] 2017-01-01 00:50
Can you share the UUID for the zombie player and their player file (in players folder, UUID filename)? A quick solution would be to delete their player file and delete topten.yml. Do that when the server is shutdown though.

**Comment by tastybento** [comment] 2017-01-02 17:41
Closing for now. Not much more that can be done here.

**Closed by tastybento** 2017-01-02 17:41 UTC
Labels: Support request, Under investigation
