### ISSUE TITLE
Heads in warp gui are backwards

### ISSUE THREAD

**Issue by steve4744** [tastybento/askyblock#398] opened 2016-12-12 02:38 UTC
When I select the "list of warps" from the island control-panel, the heads are displayed backwards, so I see the back of the players heads instead of the face.

**Comment by Poslovitch** [comment] 2016-12-12 05:26
This is not a bug of ASkyBlock, this is a bug appeared in 1.11. I had this problem with an other plugin using heads, without any solutions...

**Comment by steve4744** [comment] 2016-12-12 15:15
Its apparently fixed in MC 1.11.1....so we have to wait. Thanks.
[https://bugs.mojang.com/browse/MC-109831](url)

**Comment by Poslovitch** [comment] 2016-12-20 22:44
It's fixed in 1.11.1 which is just realeased :)

**Comment by tastybento** [comment] 2016-12-21 02:33
Good. It looks like it is still a bit unstable according to Spigot, but I'll close this now.

**Closed by tastybento** 2016-12-21 02:33 UTC
Labels: Monitoring
